language: python

# Use container-based infrastructure
sudo: false

python:
 - pypy
 - pypy3
 - 2.7
 - 3.5
 - 2.6
 - 3.2
 - 3.3
 - 3.4

install:
 - pip install -r requirements.txt
 - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install unittest2; fi

 # Coverage 4.0 doesn't support Python 3.2
 - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then pip install coverage==3.7.1; fi
 - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then pip install coverage; fi

script:
 - coverage run --source=tracery -m nose tests/test_*.py

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pyflakes . | tee >(wc -l)
 - pep8 --statistics --count .

matrix:
  fast_finish: true
